name: heed
description: A note taking app.

version: 1.0.0+1

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^0.6.9
  auto_size_text: ^2.1.0
  cloud_firestore: ^0.14.0+2
  cupertino_icons: ^1.0.0
  dartz: ^0.9.1
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  flushbar: ^1.10.4
  flutter_bloc: ^6.0.5
  flutter_hooks: ^0.14.0
  flutter_slidable: ^0.5.7
  flutter_staggered_grid_view: ^0.3.4
  freezed_annotation: ^0.12.0
  get_it: ^4.0.2
  google_fonts: ^1.1.2
  google_sign_in: ^4.5.3
  implicitly_animated_reorderable_list: ^0.3.2
  injectable: ^1.0.4
  json_annotation: ^3.0.1
  kt_dart: ^0.7.0+1
  material_floating_search_bar: ^0.3.4
  provider: ^4.3.2+2
  rxdart: ^0.24.1
  uuid: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.10
  build_runner: ^1.10.1
  font_awesome_flutter: ^8.12.0
  freezed: ^0.12.7
  injectable_generator: ^1.0.4
  json_serializable: ^3.4.1
  lint: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
